//! Build script — generates PHF maps for known fingerprint lookups.
//!
//! Reads `assets/fingerprints.csv` (if present) and emits `$OUT_DIR/known_db.rs`
//! containing two `phf::Map`s: `JA3_MAP` and `JA4_MAP`. Duplicate JA4 entries
//! cause a build failure so the DB stays consistent.

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=assets/fingerprints.csv");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("known_db.rs");
    let mut out = BufWriter::new(File::create(&dest).expect("create known_db.rs"));

    // Try to read CSV; if missing, emit empty maps so `cargo build` still works
    // before the DB is populated.
    let csv_path = Path::new("assets/fingerprints.csv");
    let mut ja3_entries: Vec<(String, String)> = Vec::new();
    let mut ja4_entries: Vec<(String, String)> = Vec::new();

    if csv_path.exists() {
        let mut rdr = csv::Reader::from_path(csv_path).expect("open fingerprints.csv");
        for result in rdr.records() {
            let record = result.expect("read csv record");
            // Expected columns: ja3,ja4,ja4s,client
            // Be tolerant: missing columns are skipped.
            let client = record.get(3).unwrap_or("").trim().to_string();
            if client.is_empty() {
                continue;
            }
            if let Some(ja3) = record.get(0) {
                let ja3 = ja3.trim();
                if !ja3.is_empty() {
                    ja3_entries.push((ja3.to_string(), client.clone()));
                }
            }
            if let Some(ja4) = record.get(1) {
                let ja4 = ja4.trim();
                if !ja4.is_empty() {
                    // Detect duplicates at codegen time.
                    assert!(
                        !ja4_entries.iter().any(|(k, _)| k == ja4),
                        "duplicate JA4 in fingerprints.csv: {ja4}"
                    );
                    ja4_entries.push((ja4.to_string(), client.clone()));
                }
            }
        }
    }

    writeln!(&mut out, "// @generated by build.rs — do not edit").unwrap();

    // JA3 map
    writeln!(&mut out, "/// JA3 map — fingerprint → client name").unwrap();
    writeln!(
        &mut out,
        "pub static JA3_MAP: phf::Map<&'static str, &'static str> = phf::phf_map!{{"
    )
    .unwrap();
    for (k, v) in &ja3_entries {
        writeln!(&mut out, "    \"{}\" => \"{}\",", escape(k), escape(v)).unwrap();
    }
    writeln!(&mut out, "}};").unwrap();

    // JA4 map
    writeln!(&mut out, "/// JA4 map — fingerprint → client name").unwrap();
    writeln!(
        &mut out,
        "pub static JA4_MAP: phf::Map<&'static str, &'static str> = phf::phf_map!{{"
    )
    .unwrap();
    for (k, v) in &ja4_entries {
        writeln!(&mut out, "    \"{}\" => \"{}\",", escape(k), escape(v)).unwrap();
    }
    writeln!(&mut out, "}};").unwrap();

    out.flush().unwrap();
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
